Bootstrap: docker
From: nfcore/base

%labels
    MAINTAINER Robert A. Petit III <robert.petit@emory.edu>
    DESCRIPTION Singularity image for Bactopia Tool summary
    VERSION 1.2.3

%environment
    PATH=/opt/conda/envs/summary/bin:$PATH
    export PATH

%files
    ./environment.yml /

%post
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin/conda clean -a
