name: meningotype
description: Serotyping of Neisseria meningitidis assemblies
keywords:
  - fasta
  - Neisseria meningitidis
  - serotype
tools:
  - meningotype:
      description: In silico serotyping and finetyping (porA and fetA) of Neisseria meningitidis
      homepage: https://github.com/MDU-PHL/meningotype
      documentation: https://github.com/MDU-PHL/meningotype
      tool_dev_url: https://github.com/MDU-PHL/meningotype
      doi: ""
      licence: ['GPL v3']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Tab-delimited result file
      pattern: "*.tsv"

authors:
  - "@rpetit3"
