name: custom_wget
description: Download files using wget
keywords:
  - download
  - wget
  - fetch
tools:
  - wget:
      description: |
        GNU Wget is a free software package for retrieving files using HTTP, HTTPS, FTP and FTPS
      homepage: https://www.gnu.org/software/wget/
      documentation: https://www.gnu.org/software/wget/manual/
      licence: ["GPL v3"]

input:
  - None

output:
  - download:
      type: file
      description: Downloaded file
      pattern: "*"
  - logs:
      type: file
      description: Log files
      pattern: "*.{log,err}"
  - nf_begin:
      type: file
      description: Nextflow begin file
      pattern: ".command.begin"
  - nf_err:
      type: file
      description: Nextflow error file
      pattern: ".command.err"
  - nf_log:
      type: file
      description: Nextflow log file
      pattern: ".command.log"
  - nf_out:
      type: file
      description: Nextflow output file
      pattern: ".command.out"
  - nf_run:
      type: file
      description: Nextflow run file
      pattern: ".command.run"
  - nf_sh:
      type: file
      description: Nextflow script file
      pattern: ".command.sh"
  - nf_trace:
      type: file
      description: Nextflow trace file
      pattern: ".command.trace"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@rpetit3"
