Bootstrap: docker
From: nfcore/base

%labels
    MAINTAINER Robert A. Petit III <robert.petit@emory.edu>
    DESCRIPTION Singularity image for Bactopia Tool phyloflash
    VERSION 1.3.0

%environment
    PATH=/opt/conda/envs/bactopia-phyloflash/bin:/opt/conda/envs/python3/bin:$PATH
    export PATH

%files
    ./environment.yml /

%post
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin/conda create -n python3 -c conda-forge python=3
    /opt/conda/bin/conda clean -a
