name: srahumanscrubber_initdb
description: Initialize human read removal database for SRA Human Scrubber
keywords:
  - human read removal
  - database
  - sra
  - scrubber
tools:
  - sra-human-scrubber:
      description: A tool to remove human reads from sequencing data
      homepage: https://github.com/ncbi/sra-human-scrubber
      documentation: https://github.com/ncbi/sra-human-scrubber/wiki
      tool_dev_url: https://github.com/ncbi/sra-human-scrubber
      doi: ""
      licence: ['Public Domain']

output:
  - db:
      type: file
      description: SRA Human Scrubber database file
      pattern: "*.human_filter.db"
  - logs:
      type: file
      description: Log files (if applicable)
      pattern: "*.{log,err}"
  - begin:
      type: file
      description: Process begin marker file
      pattern: ".command.begin"
  - err:
      type: file
      description: Process stderr log
      pattern: ".command.err"
  - log:
      type: file
      description: Process log
      pattern: ".command.log"
  - out:
      type: file
      description: Process stdout log
      pattern: ".command.out"
  - run:
      type: file
      description: Process run script
      pattern: ".command.run"
  - sh:
      type: file
      description: Process shell script
      pattern: ".command.sh"
  - trace:
      type: file
      description: Process trace log
      pattern: ".command.trace"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@rpetit3"
