name: legsta
description: In silico Legionella pneumophila sequence based typing
keywords:
  - legionella
  - pneumophila
  - typing
  - sbt
tools:
  - legsta:
      description: "In silico Legionella pneumophila sequence based typing"
      homepage: "https://github.com/tseemann/legsta"
      documentation: "https://github.com/tseemann/legsta"
      tool_dev_url: "https://github.com/tseemann/legsta"
      doi: ""
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - seqs:
      type: file
      description: FASTA file of contigs or genome
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: Tab-delimited legsta results
      pattern: "*.tsv"
  - logs:
      type: file
      description: Standard log files
      pattern: "*.{log,err}"
  - nf_logs:
      type: file
      description: Nextflow log files
      pattern: ".command.*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
