name: kraken2
description: Classifies metagenomic sequence data
keywords:
  - classify
  - metagenomics
  - fastq
  - db
tools:
  - kraken2:
      description: |
        Kraken2 is a taxonomic sequence classifier that assigns taxonomic labels to sequence reads
      homepage: https://ccb.jhu.edu/software/kraken2/
      documentation: https://github.com/DerrickWood/kraken2/wiki/Manual
      doi: 10.1186/s13059-019-1891-0
      licence: ['MIT']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
  - db:
      type: directory
      description: Kraken2 database
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - classified:
      type: file
      description: |
        Reads classified to belong to any of the taxa
        on the Kraken2 database.
      pattern: "*{fastq.gz}"
  - unclassified:
      type: file
      description: |
        Reads not classified to belong to any of the taxa
        on the Kraken2 database.
      pattern: "*{fastq.gz}"
  - report:
      type: file
      description: |
        Kraken2 report containing stats about classified
        and not classifed reads.
      pattern: "*.{report.txt}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@joseespinosa"
  - "@drpatelh"
