name: legsta
description: Typing of Legionella pneumophila assemblies
keywords:
  - fasta
  - legionella
  - typing
modules:
  - legsta
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: The final assembly in FASTA format
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Tab-delimited summary of the results
      pattern: "*.{tsv}"
  - merged_tsv:
      type: file
      description: Tab-delimited report of results from all samples
      pattern: "*.{tsv}"
docs:
  meta:
    title: legsta
    description: >-
      A Bactopia Tool which uses legsta for _in silico_ _Legionella pneumophila_
      Sequence Based Typing (SBT).
  introduction: |
    The `legsta` module uses [legsta](https://github.com/tseemann/legsta) for 
    _in silico_ _Legionella pneumophila_ Sequence Based Typing (SBT).
  output:
    tree: |
      <BACTOPIA_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── legsta
      │           ├── <SAMPLE_NAME>.tsv
      │           └── logs
      │               ├── nf-legsta.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── bactopia-runs
          └── legsta-<TIMESTAMP>
              ├── merged-results
              │   ├── legsta.tsv
              │   └── logs
              │       └── legsta-concat
              │           ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │           └── versions.yml
              └── nf-reports
                  ├── legsta-dag.dot
                  ├── legsta-report.html
                  ├── legsta-timeline.html
                  └── legsta-trace.txt
    add_note: true
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: legsta.tsv
            description: A tab-delimited file with `legsta` results from all samples
      - name: legsta
        description: |
          Below is a description of the _per-sample_ results from [legsta](https://github.com/tseemann/legsta).
        table:
          - id: <SAMPLE_NAME>.tsv
            description: A tab-delimited file with `legsta` result, see [legsta - Output](https://github.com/tseemann/legsta#output) for more details
  citations:
    - csvtk
    - legsta
