name: rgi_heatmap
description: Creates heatmaps from RGI JSON output files
keywords:
  - resistance
  - antimicrobial resistance
  - CARD
  - RGI
  - heatmap
  - visualization
tools:
  - rgi:
      description: The Resistance Gene Identifier (RGI) is a bioinformatics tool for predicting resistomes from genomes and metagenomes
      homepage: https://card.mcmaster.ca/analyze/rgi
      documentation: https://github.com/arpcard/rgi
      tool_dev_url: https://github.com/arpcard/rgi
      doi: "10.1093/nar/gkz935"
      licence: ['MIT']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - json:
      type: file
      description: RGI JSON output files
      pattern: "*.json"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - heatmap:
      type: file
      description: Heatmap files in various formats (CSV, EPS, PNG)
      pattern: "*.{csv,eps,png}"
authors:
  - "@rpetit3"
