name: mashtree
description: Quickly create a tree using Mash distances
keywords:
  - tree
  - mash
  - fasta
  - fastq
tools:
  - mashtree:
      description: Create a tree using Mash distances
      homepage: https://github.com/lskatz/mashtree
      documentation: https://github.com/lskatz/mashtree
      tool_dev_url: https://github.com/lskatz/mashtree
      doi: "https://doi.org/10.21105/joss.01762"
      licence: ['GPL v3']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - seqs:
      type: file
      description: FASTA, FASTQ, GenBank, or Mash sketch files
      pattern: "*.{fna,fna.gz,fasta,fasta.gz,fa,fa.gz,gbk,gbk.gz,fastq.gz,msh}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tree:
      type: file
      description: A Newick formatted tree file
      pattern: "*.{dnd}"
  - matrix:
      type: file
      description: A TSV matrix of pair-wise Mash distances
      pattern: "*.{tsv}"

authors:
  - "@rpetit3"
