name: sistr
description: Salmonella In Silico Typing Resource
keywords:
  - Salmonella
  - serotype
  - cgMLST
  - typing
tools:
  - sistr:
      description: Salmonella In Silico Typing Resource (SISTR) command-line tool
      homepage: https://github.com/phac-nml/sistr_cmd
      documentation: https://github.com/phac-nml/sistr_cmd
      tool_dev_url: https://github.com/phac-nml/sistr_cmd
      doi: "10.1371/journal.pone.0147101"
      licence: ['Apache-2.0']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file containing the genome assembly
      pattern: "*.{fasta,fna,fa,fasta.gz,fna.gz,fa.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: SISTR prediction results in TSV format
      pattern: "*.tsv"
  - allele_fasta:
      type: file
      description: Novel alleles in FASTA format
      pattern: "*-allele.fasta.gz"
  - allele_json:
      type: file
      description: Alleles in JSON format
      pattern: "*-allele.json.gz"
  - cgmlst_csv:
      type: file
      description: cgMLST profile in CSV format
      pattern: "*-cgmlst.csv"
authors:
  - "@rpetit3"
