name: rgi_main
description: Use RGI (Resistance Gene Identifier) to predict resistome(s) from protein or nucleotide data 
keywords:
  - resistance
  - antimicrobial resistance
  - CARD
  - RGI
tools:
  - rgi:
      description: The Resistance Gene Identifier (RGI) is a bioinformatics tool for predicting resistomes from genomes and metagenomes
      homepage: https://card.mcmaster.ca/analyze/rgi
      documentation: https://github.com/arpcard/rgi
      tool_dev_url: https://github.com/arpcard/rgi
      doi: "10.1093/nar/gkz935"
      licence: ['MIT']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file containing nucleotide or protein sequences
      pattern: "*.{fasta,fna,fa,faa,fasta.gz,fna.gz,fa.gz,faa.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - json:
      type: file
      description: RGI results in JSON format
      pattern: "*.json"
  - tsv:
      type: file
      description: RGI results in tab-separated format
      pattern: "*.txt"
authors:
  - "@rpetit3"
