name: bracken
description: Bracken (Bayesian Reestimation of Abundance with KrakEN) re-estimates abundance at any taxonomic level from Kraken2 output
keywords:
  - metagenomics
  - classification
  - kraken2
  - bracken
  - taxonomic abundance
tools:
  - bracken:
      description: Highly accurate statistical method that computes the abundance of species in DNA sequences from a metagenomics sample
      homepage: https://ccb.jhu.edu/software/bracken/
      documentation: https://ccb.jhu.edu/software/bracken/index.shtml?t=manual
      tool_dev_url: https://github.com/jenniferlu717/Bracken
      doi: 10.7717/peerj-cs.104
      licence: ["GPL v3"]
  - kraken2:
      description: Kraken2 is a taxonomic sequence classifier that assigns taxonomic labels to DNA sequences
      homepage: https://ccb.jhu.edu/software/kraken2/
      documentation: https://github.com/DerrickWood/kraken2/wiki/Manual
      tool_dev_url: https://github.com/DerrickWood/kraken2
      doi: 10.1186/s13059-019-1891-0
      licence: ["MIT"]
  - fastq-scan:
      description: FastQ-Scan is a tool for quickly gathering statistics about FASTQ files
      homepage: https://github.com/rpetit3/fastq-scan
      documentation: https://github.com/rpetit3/fastq-scan
      licence: ["MIT"]
  - krakentools:
      description: KrakenTools is a suite of scripts to be used for post-analysis of Kraken/Kraken2 results
      homepage: https://github.com/jenniferlu717/KrakenTools
      documentation: https://github.com/jenniferlu717/KrakenTools
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: List of input FastQ files
      pattern: "*.{fq,fq.gz,fastq,fastq.gz}"
  - db:
      type: file
      description: Kraken2 database (can be tar.gz)
      pattern: "*"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: Bracken summary file
      pattern: "*.bracken.tsv"
  - classified:
      type: file
      description: Reads classified by Kraken2
      pattern: "*classified*"
  - unclassified:
      type: file
      description: Reads not classified by Kraken2
      pattern: "*unclassified*"
  - kraken2_report:
      type: file
      description: Kraken2 report
      pattern: "*.kraken2.report.txt"
  - kraken2_output:
      type: file
      description: Kraken2 raw output
      pattern: "*.kraken2.output.txt"
  - bracken_report:
      type: file
      description: Bracken report
      pattern: "*.bracken.report.txt"
  - krona:
      type: file
      description: Krona HTML visualization
      pattern: "*.krona.html"
  - abundances:
      type: file
      description: Bracken abundances
      pattern: "*.bracken.abundances.txt"
  - classification:
      type: file
      description: Bracken classification
      pattern: "*.bracken.classification.txt"
  - adjusted_abundances:
      type: file
      description: Bracken adjusted abundances
      pattern: "*.bracken.adjusted.abundances.txt"
  - logs:
      type: file
      description: Process logs
      pattern: "*.{log,err}"
  - nf_begin:
      type: file
      description: Nextflow begin file
      pattern: ".command.begin"
  - nf_err:
      type: file
      description: Nextflow error file
      pattern: ".command.err"
  - nf_log:
      type: file
      description: Nextflow log file
      pattern: ".command.log"
  - nf_out:
      type: file
      description: Nextflow output file
      pattern: ".command.out"
  - nf_run:
      type: file
      description: Nextflow run file
      pattern: ".command.run"
  - nf_sh:
      type: file
      description: Nextflow script file
      pattern: ".command.sh"
  - nf_trace:
      type: file
      description: Nextflow trace file
      pattern: ".command.trace"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@rpetit3"
