#!/usr/bin/env bash
# bactopia
#
# This is a wrapper around Bactopia-AP for packaging the Conda recipe. It has
# been inspired by a similar wrapper in Will Rowe's DRAX pipeline
# (https://github.com/will-rowe/drax).
#
# By default `bactopia` will attmept to execute the main Nextflow pipeline.
# There are additional sub-commands available to help make Bactopia easier to
# use. They are:
#
#   pull - Pull (via Nextflow) the bactopia-ap GitHub repo
#
#   datasets - Download and setup useful datasets to supplement Bactopia
#
#   fofn - Create a FOFN of the input FASTQ files
#
#   version - Print Bactopia version and exit
#
# Examples:
#
# bactopia pull
# bactopia datasets --help
# bactopia fofn --help
# bactopia version
# bactopia --help
VERSION=1.2.0

# If no user input, print usage
if [[ $# == 0 ]]; then
    echo "bactopia - v${VERSION}"
    echo ""
    echo "Available Commands"
    echo "\`bactopia\` - Execute the Bactopia Nextflow pipeline"
    echo ""
    echo "\`bactopia pull\` - Pull (via Nextflow) the bactopia-ap GitHub repo"
    echo ""
    echo "\`bactopia datasets\` - Download/setup useful datasets for Bactopia"
    echo ""
    echo "\`bactopia prepare\` - Create a 'file of filenames' for input FASTQ files"
    echo ""
    echo "\`bactopia search\` - Query Taxon ID or Study Accession against ENA for input accessions"
    echo ""
    echo "\`bactopia version\` - Print Bactopia version and exit"
    echo ""
    echo "Print Usages:"
    echo "\`bactopia --help\`"
    echo "\`bactopia datasets --help\`"
    echo "\`bactopia prepare --help\`"
    echo "\`bactopia search --help\`"
    echo ""
    echo "Example Commands"
    echo "bactopia --R1 SAMPLE_R1.fastq.gz --R2 SAMPLE_R2.fastq.gz --sample SAMPLE"
    echo ""
    echo "bactopia datasets dataset-dir --species 'Staphylococcus aureus'"
    echo "bactopia --dataset dataset-dir --species 'staphylococcus-aureus' --accession SRX4563671"
    echo ""
    echo "bactopia prepare my-fastq-dir > my-fastqs.txt"
    echo "bactopia --fastqs my-fastqs.txt"
    echo ""
    echo "bactopia search PRJNA480016 --limit 20"
    echo "bactopia --accessions ena-accessions.txt"
    echo ""
    exit
fi

if [[ "$1" == "pull" ]]; then
    # Use Nextflow to pull Bactopia
    nextflow pull bactopia/bactopia -r "v${VERSION}"
elif [[ "$1" == "datasets" ]]; then
    # Run setup-datasets
    setup-datasets.py "${@:2}"
elif [[ "$1" == "prepare" ]]; then
    # Run prepare-fofn
    prepare-fofn.py "${@:2}"
elif [[ "$1" == "search" ]]; then
    # Run ena-search
    ena-search.py "${@:2}"
elif [[ "$1" == "version" ]] || [[ "$1" == "--version" ]]; then
    echo "bactopia ${VERSION}"
else
    # Execute Bactopia Nextflow pipeline
    nextflow run bactopia/bactopia "${@:1}"
fi
