name: staphopiasccmec
description: Predicts Staphylococcus aureus SCCmec type based on primers.
keywords:
  - amr
  - fasta
  - sccmec

tools:
  - staphopiasccmec:
      description: Predicts Staphylococcus aureus SCCmec type based on primers.
      homepage: https://staphopia.emory.edu
      documentation: https://github.com/staphopia/staphopia-sccmec
      tool_dev_url: https://github.com/staphopia/staphopia-sccmec
      doi: https://doi.org/10.7717/peerj.5261
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Tab-delimited results
      pattern: "*.{tsv}"

authors:
  - "@rpetit3"
