name: quast
description: Quality Assessment Tool for Genome Assemblies
keywords:
  - assembly
  - quality assessment
  - contig analysis
tools:
  - quast:
      description: Quality Assessment Tool for Genome Assemblies
      homepage: https://github.com/ablab/quast
      documentation: https://quast.sourceforge.net/docs/manual.html
      tool_dev_url: https://github.com/ablab/quast
      doi: "10.1093/bioinformatics/btt086"
      licence: ['GPL v2']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Assembly file in FASTA format
      pattern: "*.{fasta,fna,fa,fasta.gz,fna.gz,fa.gz}"
  - meta_file:
      type: file
      description: Meta file containing reference size information
      pattern: "*.txt"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Transposed report in TSV format
      pattern: "*.tsv"
  - results:
      type: file
      description: All QUAST output files
      pattern: "supplemental/*"
authors:
  - "@rpetit3"
