name: hpsuissero
description: Serotype prediction of Haemophilus parasuis assemblies
keywords:
  - bacteria
  - fasta
  - haemophilus 
tools:
  - hpsuissero:
      description: Rapid Haemophilus parasuis serotyping pipeline for Nanpore data
      homepage: https://github.com/jimmyliu1326/HpsuisSero
      documentation: https://github.com/jimmyliu1326/HpsuisSero
      tool_dev_url: https://github.com/jimmyliu1326/HpsuisSero
      doi: ""
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Assembly in FASTA format
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz,faa,faa.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Tab-delimited serotype prediction
      pattern: "*.{tsv}"

authors:
  - "@rpetit3"
