/**
 * Parse Mykrobe results to genotype *Salmonella* Typhi.
 *
 * Uses scripts from [GenoTyphi](https://github.com/katholt/genotyphi) to parse the JSON output
 * from Mykrobe. It assigns isolates to specific *S.* Typhi genotypes (e.g., 4.3.1) based on
 * the presence of specific SNPs defined in the GenoTyphi scheme.
 *
 * @status stable
 * @keywords bacteria, salmonella, typhi, genotyping, mykrobe, parser
 * @tags complexity:simple input-type:single output-type:single features:conditional-logic
 * @citation genotyphi, mccortex
 *
 * @input record(meta, json)
 * - `meta`: Groovy Record containing sample information
 * - `json`: The JSON output file generated by Mykrobe
 *
 * @output record(meta, tsv, results, logs, nf_logs, versions)
 * - `tsv`: Tab-delimited report containing the assigned GenoTyphi genotype
 */
nextflow.enable.types = true

process GENOTYPHI_PARSE {
    tag "${prefix}"
    label 'process_low'

    conda "${task.ext.condaDir}/${task.ext.toolName}"
    container "${task.ext.container}"

    input:
    record (
        meta: Record,
        json: Path
    )

    output:
    record(
        // Named fields (used downstream)
        meta: meta,
        tsv: file("${prefix}.tsv"),
        // Generic fields (used for publishing)
        results: [
            files("${prefix}.tsv")
        ],
        logs: files("*.{log,err}", optional: true),
        nf_logs: files(".command.*"),
        versions: files("versions.yml")
    )

    script:
    def _meta = meta
    prefix = task.ext.prefix ?: "${_meta.name}"

    // Create a new meta variable
    meta = record(
        id: "${prefix}-${task.process}",
        name: prefix,
        scope: task.ext.scope,
        output_dir: "${prefix}/tools/${task.ext.process_name}/${task.ext.subdir}",
        logs_dir: "${prefix}/tools/${task.ext.process_name}/${task.ext.subdir}/logs/${task.ext.logs_subdir}",
        process_name: task.ext.process_name
    )
    """
    parse_typhi_mykrobe.py \\
        --jsons ${json} \\
        --prefix ${prefix}

    # Cleanup
    mv ${prefix}_predictResults.tsv ${prefix}.tsv

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        genotyphi: \$(echo \$(genotyphi --version 2>&1) | sed 's/^.*GenoTyphi v//;' )
    END_VERSIONS
    """
}
