name: agrvate
description: Rapid identification of Staphylococcus aureus agr locus type and agr operon variants
keywords:
  - fasta
  - virulence
  - Staphylococcus aureus
tools:
  - agrvate:
      description: Rapid identification of Staphylococcus aureus agr locus type and agr operon variants.
      homepage: https://github.com/VishnuRaghuram94/AgrVATE
      documentation: https://github.com/VishnuRaghuram94/AgrVATE
      tool_dev_url: https://github.com/VishnuRaghuram94/AgrVATE
      doi: ""
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Staphylococcus aureus fasta file.
      pattern: "*.fasta"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - summary:
      type: file
      description: A summary of the agrvate assessement
      pattern: "*-summary.tab"
  - results_dir:
      type: directory
      description: Results of the agrvate assessement
      pattern: "*-results"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@abhi18av"
