Bootstrap: docker
From: nfcore/base

%labels
    MAINTAINER Robert A. Petit III <robert.petit@emory.edu>
    DESCRIPTION Singularity image for Bactopia Tool cgtree
    VERSION 1.2.2

%environment
    PATH=/opt/conda/envs/cgtree/bin:$PATH
    export PATH

%post
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin/conda clean -a
