name: spatyper
description: Computational method for finding spa types in Staphylococcus aureus
keywords:
  - Staphylococcus aureus
  - spa typing
  - repeat
tools:
  - spatyper:
      description: Computational method for finding spa types in Staphylococcus aureus
      homepage: https://github.com/HCGB-IGTP/spaTyper
      documentation: https://github.com/HCGB-IGTP/spaTyper
      tool_dev_url: https://github.com/HCGB-IGTP/spaTyper
      doi: "10.5281/zenodo.4063625"
      licence: ['LGPL v3']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file containing the genome assembly
      pattern: "*.{fasta,fna,fa,fasta.gz,fna.gz,fa.gz}"
  - repeats:
      type: file
      description: Custom repeat file
      pattern: "*.{fasta,fna,fa}"
  - repeat_order:
      type: file
      description: Custom repeat order file
      pattern: "*.txt"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: spa typing results in TSV format
      pattern: "*.tsv"
authors:
  - "@rpetit3"
