name: "ariba_run"
description: Query input FASTQs against Ariba formatted databases
keywords:
  - fastq
  - assembly
  - resistance
  - virulence
tools:
  - "ariba":
      description: "ARIBA: Antibiotic Resistance Identification By Assembly"
      homepage: "https://sanger-pathogens.github.io/ariba/"
      documentation: "https://sanger-pathogens.github.io/ariba/"
      tool_dev_url: "https://github.com/sanger-pathogens/ariba"
      doi: "110.1099/mgen.0.000131"
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: Paired-end reads in FASTQ format
      pattern: "*_R[1|2].{fastq.gz,fq.gz}"
  - db:
      type: file
      description: An Ariba prepared database
      pattern: "*.tar.gz"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - results:
      type: file
      description: A directory of Ariba analysis outputs
      pattern: "*"

authors:
  - "@rpetit3"
