name: snippy
description: Rapid variant calling from Illumina sequence reads with optional core-SNP phylogeny
icon: false
keywords:
  - alignment
  - core-snp
  - phylogeny
  - variants
modules:
  - snippy_run
input:
  - meta:
    type: map
    description: |
      Groovy Map containing sample information
      e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
      pattern: "*.fastq.gz"
  - reference:
      type: file
      description: Reference genome in GenBank format
      pattern: "*.{gbk,gbk.gz}"
output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
docs:
  meta:
    title: snippy
    description: >-
      A Bactopia Tool which uses Snippy to call SNPs and InDels against a reference and
      create a core-SNP phylogeny using IQ-Tree and Gubbins.
  introduction: |
    The `snippy` subworkflow allows you to call SNPs and InDels against a reference with
    [Snippy](https://github.com/tseemann/snippy).
