name: bactopia_samplesheet
description: Create sample sheets for Teton workflow based on species classification
keywords:
  - bactopia
  - sample sheet
  - classification
  - teton
tools:
  - sizemeup:
      description: Get genome size based on species
      homepage: https://github.com/bactopia/bactopia-tools
      documentation: https://github.com/bactopia/bactopia-tools
      tool_dev_url: https://github.com/bactopia/bactopia-tools
      licence: ['MIT']
  - teton:
      description: Prepare sample sheets for Teton workflow
      homepage: https://github.com/bactopia/bactopia-tools
      documentation: https://github.com/bactopia/bactopia-tools
      tool_dev_url: https://github.com/bactopia/bactopia-tools
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - classification:
      type: file
      description: Classification results file
      pattern: "*.txt"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bacteria_tsv:
      type: file
      description: Sample sheet for bacterial samples
      pattern: "*.bacteria.tsv"
  - nonbacteria_tsv:
      type: file
      description: Sample sheet for non-bacterial samples
      pattern: "*.nonbacteria.tsv"
  - sizemeup:
      type: file
      description: Genome size predictions
      pattern: "*-sizemeup.txt"
  - logs:
      type: file
      description: Logs from the process
      pattern: "*.{log,err}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@rpetit3"
