name: snpdists
description: Pairwise SNP distance matrix from a FASTA sequence alignment
keywords:
  - snp-dists
  - distance-matrix
tools:
  - snpdists:
      description: Convert a FASTA alignment to SNP distance matrix
      homepage: https://github.com/tseemann/snp-dists
      documentation: https://github.com/tseemann/snp-dists
      tool_dev_url: https://github.com/tseemann/snp-dists
      doi: ""
      licence: ['GPL v3']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - alignment:
      type: file
      description: The input FASTA sequence alignment file
      pattern: "*.{fasta,fasta.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: The output TSV file containing SNP distance matrix
      pattern: "*.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@abhi18av"
