name: snippy_run
description: Rapid haploid variant calling
keywords:
  - variant
  - fastq
  - bacteria
tools:
  - snippy:
      description: "Rapid bacterial SNP calling and core genome alignments"
      homepage: "https://github.com/tseemann/snippy"
      documentation: "https://github.com/tseemann/snippy"
      tool_dev_url: "https://github.com/tseemann/snippy"
      doi: ""
      licence: "['GPL v2']"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
      pattern: "*.{fq,fastq,fq.gz,fastq.gz}"
  - index:
      type: file
      description: Reference genome in GenBank (preferred) or FASTA format
      pattern: "*.{gbk,gbk.gz,fa,fa.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tab:
      type: file
      description: A simple tab-separated summary of all the variants
      pattern: "*.tab"
  - csv:
      type: file
      description: A comma-separated version of the .tab file
      pattern: "*.csv"
  - html:
      type: file
      description: A HTML version of the .tab file
      pattern: "*.html"
  - vcf:
      type: file
      description: The final annotated variants in VCF format
      pattern: "*.vcf"
  - bed:
      type: file
      description: The variants in BED format
      pattern: "*.bed"
  - gff:
      type: file
      description: The variants in GFF3 format
      pattern: "*.gff"
  - bam:
      type: file
      description: The alignments in BAM format. Includes unmapped, multimapping reads. Excludes duplicates.
      pattern: "*.bam"
  - bai:
      type: file
      description: Index for the .bam file
      pattern: "*.bam.bai"
  - log:
      type: file
      description: A log file with the commands run and their outputs
      pattern: "*.log"
  - aligned_fa:
      type: file
      description: A version of the reference but with - at position with depth=0 and N for 0 < depth < --mincov (does not have variants)
      pattern: "*.aligned.fa"
  - consensus_fa:
      type: file
      description: A version of the reference genome with all variants instantiated
      pattern: "*.consensus.fa"
  - consensus_subs_fa:
      type: file
      description: A version of the reference genome with only substitution variants instantiated
      pattern: "*.consensus.subs.fa"
  - raw_vcf:
      type: file
      description: The unfiltered variant calls from Freebayes
      pattern: "*.raw.vcf"
  - filt_vcf:
      type: file
      description: The filtered variant calls from Freebayes
      pattern: "*.filt.vcf"
  - vcf_gz:
      type: file
      description: Compressed .vcf file via BGZIP
      pattern: "*.vcf.gz"
  - vcf_csi:
      type: file
      description: Index for the .vcf.gz via bcftools index
      pattern: "*.vcf.gz.csi"
  - txt:
      type: file
      description: Tab-separated columnar list of statistics
      pattern: "*.txt"
authors:
  - "@rpetit3"
