name: sistr
description: Serovar prediction of salmonella assemblies
keywords:
  - bacteria
  - fasta
  - salmonella
tools:
  - sistr:
      description: Salmonella In Silico Typing Resource (SISTR) commandline tool for serovar prediction
      homepage: https://github.com/phac-nml/sistr_cmd
      documentation: https://github.com/phac-nml/sistr_cmd
      tool_dev_url: https://github.com/phac-nml/sistr_cmd
      doi: "10.1371/journal.pone.0147101"
      licence: ['Apache-2.0']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Nucleotide or protein sequences in FASTA format
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz,faa,faa.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: SISTR serovar prediction
      pattern: "*.{tsv}"
  - allele_json:
      type: file
      description: Allele sequences and info to JSON
      pattern: "*.{json}"
  - allele_fasta:
      type: file
      description: FASTA file destination of novel cgMLST alleles
      pattern: "*.{fasta}"
  - cgmlst_csv:
      type: file
      description: CSV file destination for cgMLST allelic profiles
      pattern: "*.{csv}"

authors:
  - "@rpetit3"
