name: blast_blastx
description: Searches protein databases using a translated nucleotide query
keywords:
  - fasta
  - blast
  - blastx
  - protein database
  - nucleotide query
tools:
  - blast:
      description: |
        BLAST finds regions of similarity between biological sequences.
      homepage: https://blast.ncbi.nlm.nih.gov/Blast.cgi
      documentation: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=Blastdocs
      doi: 10.1016/S0022-2836(05)80360-2
      licence: ["US-Government-Work"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - blastdb:
      type: file
      description: BLAST protein database tarball
      pattern: "*.tar.gz"
  - query:
      type: file
      description: Input fasta file containing nucleotide query sequences
      pattern: "*.{fa,fasta,fna,fa.gz,fasta.gz,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: Tab-separated file containing blastx hits
      pattern: "*.blastx.tsv"
  - logs:
      type: file
      description: Process logs
      pattern: "*.{log,err}"
  - nf_begin:
      type: file
      description: Nextflow begin file
      pattern: ".command.begin"
  - nf_err:
      type: file
      description: Nextflow error file
      pattern: ".command.err"
  - nf_log:
      type: file
      description: Nextflow log file
      pattern: ".command.log"
  - nf_out:
      type: file
      description: Nextflow output file
      pattern: ".command.out"
  - nf_run:
      type: file
      description: Nextflow run file
      pattern: ".command.run"
  - nf_sh:
      type: file
      description: Nextflow script file
      pattern: ".command.sh"
  - nf_trace:
      type: file
      description: Nextflow trace file
      pattern: ".command.trace"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@rpetit3"
