name: gtdbtk_classifywf
description: GTDB-Tk classification workflow for bacterial and archaeal genomes
keywords:
  - gtdb
  - taxonomy
  - classification
  - archaea
  - bacteria
tools:
  - gtdbtk:
      description: "A toolkit for assigning objective taxonomic classifications to bacterial and archaeal genomes"
      homepage: "https://github.com/Ecogenomics/GTDBTk"
      documentation: "https://ecogenomics.github.io/GTDBTk/"
      tool_dev_url: "https://github.com/Ecogenomics/GTDBTk"
      doi: "10.1093/bioinformatics/btz848"
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fna:
      type: file
      description: Genome assemblies in FASTA format
      pattern: "*.{fna,fna.gz,fa,fa.gz,fasta,fasta.gz}"
  - db:
      type: file or directory
      description: GTDB database directory or tarball
      pattern: "*"

output:
  - results:
      type: directory
      description: Directory containing all GTDB-Tk output files
      pattern: "results/*"
  - tsv:
      type: file
      description: Summary classification file
      pattern: "results/*.summary.tsv"
  - logs:
      type: file
      description: Standard log files
      pattern: "*.{log,err}"
  - nf_logs:
      type: file
      description: Nextflow log files
      pattern: ".command.*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
