name: ssuissero
description: In silico serotyping of Streptococcus suis
keywords:
  - Streptococcus suis
  - serotype
  - typing
tools:
  - ssuissero:
      description: Rapid determination of Streptococcus suis serotype from genome sequence
      homepage: https://github.com/jimmyliu1326/SsuisSero
      documentation: https://github.com/jimmyliu1326/SsuisSero
      tool_dev_url: https://github.com/jimmyliu1326/SsuisSero
      doi: ""
      licence: ['MIT']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file containing the genome assembly
      pattern: "*.{fasta,fna,fa,fasta.gz,fna.gz,fa.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: SsuisSero results in TSV format
      pattern: "*.tsv"
authors:
  - "@rpetit3"
