Bootstrap: docker
From: nfcore/base

%labels
    MAINTAINER Robert A. Petit III <robert.petit@emory.edu>
    DESCRIPTION Singularity image for Bactopia Tool: roary
    VERSION 1.5.x

%environment
    PATH=/opt/conda/envs/bactopia-roary/bin:$PATH
    export PATH

%files
    tools/roary/environment-linux.yml /

%post
    /opt/conda/bin/conda env create -f /environment-linux.yml
    /opt/conda/bin/conda clean -a
