name: scoary
description: Use pangenome outputs for GWAS
keywords:
  - gwas
  - pangenome
  - prokaryote
tools:
  - scoary:
      description: Microbial pan-GWAS using the output from Roary
      homepage: https://github.com/AdmiralenOla/Scoary
      documentation: https://github.com/AdmiralenOla/Scoary
      tool_dev_url: https://github.com/AdmiralenOla/Scoary
      doi: "10.1186/s13059-016-1108-8"
      licence: ['GPL v3']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - genes:
      type: file
      description: A presence/absence matrix of genes in the pan-genome
      pattern: "*.csv"
  - traits:
      type: file
      description: A CSV file containing trait information per-sample
      pattern: "*.csv"
  - tree:
      type: file
      description: A Newick formtted tree for phylogenetic analyses
      pattern: "*.{dnd,nwk,treefile}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - csv:
      type: file
      description: Gene associations in a CSV file per trait
      pattern: "*.csv"

authors:
  - "@rpetit3"
