name: meningotype
description: Serotyping of Neisseria meningitidis
icon: false
tags:
  - fasta
  - Neisseria meningitidis
  - serotype
modules:
  - meningotype
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Neisseria meningitidis fasta file.
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample meningotype result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all meningotype result files
      pattern: "meningotype.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'

docs:
  meta:
    title: meningotype
    description: >-
      A Bactopia Tool which uses meningotype for _in silico_ typing of
      _Neisseria meningitidis_ genomes.
  introduction: |
    The `meningotype` module uses [meningotype](https://github.com/MDU-PHL/meningotype) 
    for _in silico_ typing of _Neisseria meningitidis_ genomes. It uses the contigs from 
    assemblies to determine the serotype, MLST, finetyping  (_porA_, _fetA_, _porB_), and 
    Bexsero antigen sequence typing (BAST) (_fHbp_, _NHBA_, _NadA_, _PorA_).
  output:
    tree: |
      <BACTOPIA_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── meningotype
      │           ├── <SAMPLE_NAME>.tsv
      │           └── logs
      │               ├── nf-meningotype.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── bactopia-runs
          └── meningotype-<TIMESTAMP>
              ├── merged-results
              │   ├── logs
              │   │   └── meningotype-concat
              │   │       ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │   │       └── versions.yml
              │   └── meningotype.tsv
              └── nf-reports
                  ├── meningotype-dag.dot
                  ├── meningotype-report.html
                  ├── meningotype-timeline.html
                  └── meningotype-trace.txt
    add_note: true
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: meningotype.tsv
            description: A merged TSV file with `meningotype` results from all samples
      - name: meningotype
        description: |
          Below is a description of the _per-sample_ results from [meningotype](https://github.com/MDU-PHL/meningotype) .
        table:
          - id: <SAMPLE_NAME>.tsv
            description: A tab-delimited file with `meningotype` result
  citations:
    - csvtk
    - meningotype
