name: kleborate
description: Screening genomic assemblies of Klebsiella for clinically relevant determinants
keywords:
  - klebsiella
  - resistance
  - virulence
  - typing
tools:
  - kleborate:
      description: "Screening genomic assemblies of Klebsiella for clinically relevant determinants"
      homepage: "https://github.com/klebgenomics/Kleborate"
      documentation: "https://github.com/klebgenomics/Kleborate/wiki"
      tool_dev_url: "https://github.com/klebgenomics/Kleborate"
      doi: "10.1038/s41467-021-24448-3"
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fastas:
      type: file
      description: Assembly files in FASTA format
      pattern: "*.{fa,fasta,fna}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - txt:
      type: file
      description: Tab-delimited Kleborate results
      pattern: "*.txt"
  - logs:
      type: file
      description: Standard log files
      pattern: "*.{log,err}"
  - nf_logs:
      type: file
      description: Nextflow log files
      pattern: ".command.*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
