Bootstrap: docker
From: nfcore/base

%labels
    MAINTAINER Robert A. Petit III <robert.petit@emory.edu>
    DESCRIPTION Singularity image for Bactopia Tool pirate
    VERSION 1.4.0

%environment
    PATH=/opt/conda/envs/bactopia-pirate/bin:$PATH
    export PATH

%files
    tools/pirate/environment.yml /

%post
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin/conda clean -a
