name: ngmaster
description: Serotyping Neisseria gonorrhoeae assemblies
keywords:
  - fasta
  - Neisseria gonorrhoeae
  - serotype
tools:
  - ngmaster:
      description: In silico multi-antigen sequence typing for Neisseria gonorrhoeae (NG-MAST)
      homepage: https://github.com/MDU-PHL/ngmaster/blob/master/README.md
      documentation: https://github.com/MDU-PHL/ngmaster/blob/master/README.md
      tool_dev_url: https://github.com/MDU-PHL/ngmaster
      doi: "10.1099/mgen.0.000076"
      licence: ['GPL v3 only']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Tab-delimited result file
      pattern: "*.tsv"

authors:
  - "@rpetit3"
