name: hpsuissero
description: Serotyping of Haemophilus parasuis
keywords:
  - haemophilus
  - parasuis
  - serotype
  - typing
tools:
  - hpsuissero:
      description: "Rapid serotyping tool for Haemophilus parasuis"
      homepage: "https://github.com/jimmyliu1326/HpsuisSero"
      documentation: "https://github.com/jimmyliu1326/HpsuisSero"
      tool_dev_url: "https://github.com/jimmyliu1326/HpsuisSero"
      doi: ""
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Assembly in FASTA format
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: Tab-delimited serotyping results
      pattern: "*.tsv"
  - logs:
      type: file
      description: Standard log files
      pattern: "*.{log,err}"
  - nf_logs:
      type: file
      description: Nextflow log files
      pattern: ".command.*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
