name: seqsero2
description: Salmonella serotype prediction from reads and assemblies
keywords:
  - fasta
  - fastq
  - salmonella
  - sertotype
tools:
  - seqsero2:
      description: Salmonella serotype prediction from genome sequencing data
      homepage: https://github.com/denglab/SeqSero2
      documentation: https://github.com/denglab/SeqSero2
      tool_dev_url: https://github.com/denglab/SeqSero2
      doi: "10.1128/AEM.01746-19"
      licence: ['GPL v2']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - seqs:
      type: file
      description: FASTQ or FASTA formated sequences
      pattern: "*.{fq.gz,fastq.gz,fna.gz,fna,fasta.gz,fasta,fa.gz,fa}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - log:
      type: file
      description: A log of serotype antigen results
      pattern: "*_log.txt"
  - tsv:
      type: file
      description: Tab-delimited summary of the SeqSero2 results
      pattern: "*_result.tsv"
  - txt:
      type: file
      description: Detailed summary of the SeqSero2 results
      pattern: "*_result.txt"

authors:
  - "@rpetit3"
