name: gamma
description: Identification, classification, and annotation of translated gene matches
icon: false
tags:
  - antimicrobial resistance
  - fasta
  - virulence
modules:
  - gamma
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: |
        An assembly to screen
  - db:
      type: file
      description: |
        A gene database in FASTA format to screen against
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - gamma:
      type: file
      description: GAMMA file with annotated gene matches
      pattern: "*.gamma"
  - psl:
      type: file
      description: PSL file with all gene matches found
      pattern: "*.psl"
  - gff:
      type: file
      description: GFF file with the gene matches
      pattern: "*.gff"
  - fasta:
      type: file
      description: multifasta file of the gene matches
      pattern: "*.fasta"
docs:
  meta:
    title: gamma
    description: >-
      A Bactopia Tool which uses GAMMA to identify, classify, and annotate translated
      gene matches from assemblies.
  introduction: |
    The `gamma` module uses [GAMMA](https://github.com/rastanton/GAMMA) to identify, classify, and annotate 
    translated gene matches from assemblies.
  output:
    tree: |
      <BACTOPIA_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── gamma
      │           └── gamma
      │               ├── <SAMPLE_NAME>.gamma
      │               ├── <SAMPLE_NAME>.psl
      │               └── logs
      │                   ├── nf-gamma.{begin,err,log,out,run,sh,trace}
      │                   └── versions.yml
      └── bactopia-runs
          └── gamma-<TIMESTAMP>
              ├── merged-results
              │   ├── gamma.tsv
              │   └── logs
              │       └── gamma-concat
              │           ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │           └── versions.yml
              └── nf-reports
                  ├── gamma-dag.dot
                  ├── gamma-report.html
                  ├── gamma-timeline.html
                  └── gamma-trace.txt
    add_note: false
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: gamma.tsv
            description: A merged TSV file with `GAMMA` results from all samples
      - name: GAMMA
        description: |
          Below is a description of the _per-sample_ results from [GAMMA](https://github.com/rastanton/GAMMA).
        table:
          - id: <SAMPLE_NAME>.fasta
            description: Annotated gene sequences is FASTA format
          - id: <SAMPLE_NAME>.gamma
            description: A TSV file with annotated gene matches
          - id: <SAMPLE_NAME>.gff
            description: Annotated gene matches is GFF3 format
          - id: <SAMPLE_NAME>.psl
            description: A PSL file with BLAT gene alignments
  citations:
    - gamma
