name: "mcroni"
description: Analysis of mcr-1 gene (mobilized colistin resistance) for sequence variation
keywords:
  - resistance
  - fasta
tools:
  - "mcroni":
      description: "Scripts for finding and processing promoter variants upstream of mcr-1"
      homepage: "https://github.com/liampshaw/mcroni"
      documentation: "https://github.com/liampshaw/mcroni"
      tool_dev_url: "https://github.com/liampshaw/mcroni"
      doi: ""
      licence: "['MIT']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A fasta file.
      pattern: "*.{fasta.gz,fasta,fa.gz,fa,fna.gz,fna}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: mcroni results in TSV format
      pattern: "*.tsv"
  - fa:
      type: file
      description: mcr-1 matching sequences
      pattern: "*.fa"

authors:
  - "@rpetit3"
