name: hpsuissero
description: Serotype prediction of _Haemophilus parasuis_ assemblies
keywords:
  - bacteria
  - fasta
  - haemophilus
modules:
  - hpsuissero
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: The final assembly in FASTA format
      pattern: "*.{fna,fna.gz}"
output:
  - tsv:
      type: file
      description: A summary of the per-sample serotype predictions
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all serotype predictions
      pattern: "ectyper.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'

docs:
  meta:
    title: hpsuissero
    description: >-
      A Bactopia Tool which uses HpsuisSero to predict the serotype of _Haemophilus parasuis_
      assemblies.
  introduction: |
    The `hpsuissero` module uses [HpsuisSero](https://github.com/jimmyliu1326/HpsuisSero) to predict
    the serotype of _Haemophilus parasuis_ assemblies.
  output:
    tree: |
      <BACTOPIA_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── hpsuissero
      │           ├── <SAMPLE_NAME>_serotyping_res.tsv
      │           └── logs
      │               ├── nf-hpsuissero.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── bactopia-runs
          └── hpsuissero-<TIMESTAMP>
              ├── merged-results
              │   ├── hpsuissero.tsv
              │   └── logs
              │       └── hpsuissero-concat
              │           ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │           └── versions.yml
              └── nf-reports
                  ├── hpsuissero-dag.dot
                  ├── hpsuissero-report.html
                  ├── hpsuissero-timeline.html
                  └── hpsuissero-trace.txt
    add_note: true
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: hpsuissero.tsv
            description: A merged TSV file with `HpsuisSero` results from all samples
      - name: HpsuisSero
        description: |
          Below is a description of the _per-sample_ results from [HpsuisSero](https://github.com/jimmyliu1326/HpsuisSero).
        table:
          - id: <SAMPLE_NAME>_serotyping_res.tsv
            description: A tab-delimited file with `HpsuisSero` result
  citations:
    - csvtk
    - hpsuissero
