name: roary
description: Calculate pan-genome from annotated bacterial assemblies in GFF3 format
keywords:
  - gff
  - pan-genome
  - alignment
tools:
  - roary:
      description: Rapid large-scale prokaryote pan genome analysis
      homepage: http://sanger-pathogens.github.io/Roary/
      documentation: http://sanger-pathogens.github.io/Roary/
      tool_dev_url: https://github.com/sanger-pathogens/Roary/
      doi: "http://dx.doi.org/10.1093/bioinformatics/btv421"
      licence: ['GPL v3']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - gff:
      type: file
      description: A set of GFF3 formatted files
      pattern: "*.{gff}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - results:
      type: directory
      description: Directory containing Roary result files
      pattern: "*/*"
  - aln:
      type: file
      description: Core-genome alignment produced by Roary (Optional)
      pattern: "*.{aln}"

authors:
  - "@rpetit3"
