name: abricate_run
description: Screen assemblies for antimicrobial resistance against multiple databases
keywords:
  - bacteria
  - assembly
  - antimicrobial reistance
tools:
  - abricate:
      description: Mass screening of contigs for antibiotic resistance genes
      homepage: https://github.com/tseemann/abricate
      documentation: https://github.com/tseemann/abricate
      tool_dev_url: https://github.com/tseemann/abricate
      doi: ""
      licence: ['GPL v2', 'GPL v2']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - assembly:
      type: file
      description: FASTA, GenBank or EMBL formatted file
      pattern: "*.{fa,fasta,fna,fa.gz,fasta.gz,fna.gz,gbk,gbk.gz,embl,embl.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - report:
      type: file
      description: Tab-delimited report of results
      pattern: "*.{txt}"

authors:
  - "@rpetit3"
