name: "PhiSpy"
description: Predict prophages in bacterial genomes
keywords:
  - genomics
  - virus
  - phage
  - prophage
  - annotation
  - identification
tools:
  - "phispy":
      description: "Prophage finder using multiple metrics"
      homepage: "https://github.com/linsalrob/PhiSpy/blob/master/README.md"
      documentation: "https://github.com/linsalrob/PhiSpy/blob/master/README.md"
      tool_dev_url: "https://github.com/linsalrob/PhiSpy/"
      doi: "10.1093/nar/gks406"
      licence: "['MIT']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - gbk:
      type: file
      description: Genome file in .gbk or .gbff format.
      pattern: "*.{gbk,gbff}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Coordinates of each prophage identified in the genome
      pattern: "*.{tsv}"
  - information:
      type: file
      description: Prophage information details
      pattern: "*_prophage_information.tsv"
  - bacteria_fasta:
      type: file
      description: Bacterial sequences with prophages removed
      pattern: "*_bacteria.fasta"
  - bacteria_gbk:
      type: file
      description: Bacterial GenBank file with prophages removed
      pattern: "*_bacteria.gbk"
  - phage_fasta:
      type: file
      description: Phage sequences
      pattern: "*_phage.fasta"
  - phage_gbk:
      type: file
      description: Phage GenBank file
      pattern: "*_phage.gbk"
  - prophage_gff:
      type: file
      description: Prophage predictions in GFF3 format
      pattern: "*_prophage.gff3"
  - prophage_tbl:
      type: file
      description: Prophage predictions in table format
      pattern: "*_prophage.tbl"
  - prophage_tsv:
      type: file
      description: Prophage predictions in TSV format
      pattern: "*_prophage.tsv"

authors:
  - "@rpetit3"
