name: snpdists
description: Create a SNP distance matrix from a multiple sequence alignment
keywords:
  - SNP
  - distance
  - matrix
  - alignment
tools:
  - snpdists:
      description: Pairwise SNP distance matrix from a FASTA sequence alignment
      homepage: https://github.com/tseemann/snp-dists
      documentation: https://github.com/tseemann/snp-dists
      tool_dev_url: https://github.com/tseemann/snp-dists
      doi: ""
      licence: ['GPL v3']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - alignment:
      type: file
      description: Multiple sequence alignment in FASTA format
      pattern: "*.{fasta,fna,fa,aln,aln.gz,fasta.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Pairwise SNP distance matrix
      pattern: "*.tsv"
authors:
  - "@rpetit3"
