name: lissero
description: Serogrouping Listeria monocytogenes assemblies
keywords:
  - fasta
  - Listeria monocytogenes
  - serogroup
tools:
  - lissero:
      description: In silico serotyping of Listeria monocytogenes
      homepage: https://github.com/MDU-PHL/LisSero/blob/master/README.md
      documentation: https://github.com/MDU-PHL/LisSero/blob/master/README.md
      tool_dev_url: https://github.com/MDU-PHL/lissero
      doi: ""
      licence: ['GPL v3']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Tab-delimited result file
      pattern: "*.tsv"

authors:
  - "@rpetit3"

