name: hicap
description: In silico typing of the H. influenzae capsule locus
keywords:
  - haemophilus
  - influenzae
  - capsule
  - typing
  - serotype
tools:
  - hicap:
      description: "In silico typing of the H. influenzae capsule locus"
      homepage: "https://github.com/scwatts/hicap"
      documentation: "https://github.com/scwatts/hicap"
      tool_dev_url: "https://github.com/scwatts/hicap"
      doi: "10.1128/JCM.00190-19"
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Assembly in FASTA format
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"
  - database_dir:
      type: directory
      description: Optional path to database directory
      pattern: "*"
  - model_fp:
      type: file
      description: Optional path to prodigal model file
      pattern: "*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - gbk:
      type: file
      description: GenBank file of cap locus (optional)
      pattern: "*.gbk"
  - svg:
      type: file
      description: SVG visualization of cap locus (optional)
      pattern: "*.svg"
  - tsv:
      type: file
      description: Tab-delimited hicap results
      pattern: "*.tsv"
  - logs:
      type: file
      description: Standard log files
      pattern: "*.{log,err}"
  - nf_logs:
      type: file
      description: Nextflow log files
      pattern: ".command.*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
