name: emmtyper
description: EMM typing of Streptococcus pyogenes assemblies
keywords:
  - fasta
  - Streptococcus pyogenes
  - typing
tools:
  - emmtyper:
      description: Streptococcus pyogenes in silico EMM typer
      homepage: https://github.com/MDU-PHL/emmtyper
      documentation: https://github.com/MDU-PHL/emmtyper
      tool_dev_url: https://github.com/MDU-PHL/emmtyper
      doi: ""
      licence: ['GNU General Public v3 (GPL v3)']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Tab-delimited result file
      pattern: "*.tsv"

authors:
  - "@rpetit3"
