name: "pbptyper"
description: Assign PBP type of Streptococcus pneumoniae assemblies
keywords:
  - bacteria
  - pbp
  - fasta
  - assembly
tools:
  - "pbptyper":
      description: "In silico Penicillin Binding Protein (PBP) typer for Streptococcus pneumoniae assemblies"
      homepage: "https://github.com/rpetit3/pbptyper"
      documentation: "https://github.com/rpetit3/pbptyper"
      tool_dev_url: "https://github.com/rpetit3/pbptyper"
      doi: ""
      licence: "['MIT']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: An assembly in FASTA format
      pattern: "*.{fasta,fasta.gz,fna,fna.gz,fa,fa.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: A tab-delimited file with the predicted PBP type
      pattern: "*.tsv"
  - blast:
      type: file
      description: A tab-delimited file of all blast hits
      pattern: "*.tblastn.tsv"

authors:
  - "@rpetit3"
