name: bakta_run
description: Bakta is a rapid & standardized annotation of bacterial genomes & plasmids
keywords:
  - annotation
  - fasta
  - genome
tools:
  - bakta:
      description: Bakta is a tool for the rapid & standardized annotation of bacterial genomes and plasmids
      homepage: https://github.com/oschwengers/bakta
      documentation: https://github.com/oschwengers/bakta
      tool_dev_url: https://github.com/oschwengers/bakta
      doi: "10.1099/mgen.0.000685"
      licence: ["GPL v3"]
  - blast+:
      description: |
        BLAST finds regions of similarity between biological sequences.
      homepage: https://blast.ncbi.nlm.nih.gov/Blast.cgi
      documentation: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs
      doi: 10.1016/S0022-2836(05)80360-2
      licence: ["US-Government-Work"]
  - gzip:
      description: |
        gzip is a single-file/stream lossless data compression utility, where the resulting
        compressed file generally has the suffix .gz
      documentation: https://www.gnu.org/software/gzip/manual/gzip.html
      licence: ["GPL-3.0-or-later"]
      

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Genome assembly in FASTA format
      pattern: "*.{fa,fna,fasta}"
  - db:
      type: file
      description: Bakta database or tarball
  - proteins:
      type: file
      description: Fasta file of trusted proteins to first annotate from
      pattern: "*.{fa,faa,fasta}"
  - prodigal_tf:
      type: file
      description: Training file to use for CDS prediction
      pattern: "*.{tf}"
  - replicons:
      type: file
      description: Replicons/plasmids file for replicon detection
      pattern: "*.{tsv}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - annotations:
      type: tuple
      description: Tuple containing the main annotation files (fna, faa, gff3)
      pattern: "*.{fna,faa,gff3}"
  - embl:
      type: file
      description: Annotations in EMBL format
      pattern: "*.embl"
  - faa:
      type: file
      description: Protein CDS sequences
      pattern: "*.faa"
  - ffn:
      type: file
      description: Nucleotide CDS sequences
      pattern: "*.ffn"
  - fna:
      type: file
      description: Nucleotide sequences of the features
      pattern: "*.fna"
  - gbff:
      type: file
      description: Annotations in GenBank format
      pattern: "*.gbff"
  - gff:
      type: file
      description: Annotations in GFF3 format
      pattern: "*.gff3"
  - hypotheticals_tsv:
      type: file
      description: Summary of hypothetical proteins
      pattern: "*.hypotheticals.tsv"
  - hypotheticals_faa:
      type: file
      description: Hypothetical protein sequences
      pattern: "*.hypotheticals.faa"
  - tsv:
      type: file
      description: Summary of annotated features
      pattern: "*.tsv"
  - txt:
      type: file
      description: Sequence and annotation statistics
      pattern: "*.txt"
  - blastdb:
      type: file
      description: BLAST database of contigs, genes, and proteins
      pattern: "*-blastdb.tar.gz"
  - logs:
      type: file
      description: Bakta logs
      pattern: "*.{log,err}"
  - nf_begin:
      type: file
      description: Nextflow begin file
      pattern: ".command.begin"
  - nf_err:
      type: file
      description: Nextflow error file
      pattern: ".command.err"
  - nf_log:
      type: file
      description: Nextflow log file
      pattern: ".command.log"
  - nf_out:
      type: file
      description: Nextflow output file
      pattern: ".command.out"
  - nf_run:
      type: file
      description: Nextflow run file
      pattern: ".command.run"
  - nf_sh:
      type: file
      description: Nextflow script file
      pattern: ".command.sh"
  - nf_trace:
      type: file
      description: Nextflow trace file
      pattern: ".command.trace"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@oschwengers"
  - "@rpetit3"
