name: staphopiasccmec
description: Predicts SCCmec types for Staphylococcus aureus genomes
keywords:
  - staphylococcus
  - SCCmec
  - typing
tools:
  - staphopia-sccmec:
      description: Predicts SCCmec types from S. aureus assemblies
      homepage: https://github.com/staphopia/staphopia-sccmec
      documentation: https://github.com/staphopia/staphopia-sccmec
      tool_dev_url: https://github.com/staphopia/staphopia-sccmec
      doi: ""
      licence: ['MIT']

input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - fasta:
      type: file
      description: Assembly file in FASTA format
      pattern: "*.{fa,fasta,fna,fa.gz,fasta.gz,fna.gz}"

output:
  - tsv:
      type: file
      description: TSV file with SCCmec typing results
      pattern: "*.tsv"
  - logs:
      type: file
      description: Log files (if applicable)
      pattern: "*.{log,err}"
  - begin:
      type: file
      description: Process begin marker file
      pattern: ".command.begin"
  - err:
      type: file
      description: Process stderr log
      pattern: ".command.err"
  - log:
      type: file
      description: Process log
      pattern: ".command.log"
  - out:
      type: file
      description: Process stdout log
      pattern: ".command.out"
  - run:
      type: file
      description: Process run script
      pattern: ".command.run"
  - sh:
      type: file
      description: Process shell script
      pattern: ".command.sh"
  - trace:
      type: file
      description: Process trace log
      pattern: ".command.trace"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@rpetit3"
