name: seroba_run
description: k-mer based Streptococcus pneumoniae serotyping
keywords:
  - Streptococcus pneumoniae
  - serotype
  - k-mer
tools:
  - seroba:
      description: SeroBA is a k-mer based Pipeline to identify the Serotype from Illumina NGS reads for Streptococcus pneumoniae
      homepage: https://github.com/sanger-pathogens/seroba
      documentation: https://github.com/sanger-pathogens/seroba
      tool_dev_url: https://github.com/sanger-pathogens/seroba
      doi: "10.1099/mgen.0.000186"
      licence: ['GPL v3']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: Paired-end FASTQ files
      pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: SeroBA prediction results
      pattern: "*.tsv"
  - txt:
      type: file
      description: Detailed serogroup information
      pattern: "detailed_serogroup_info.txt"
authors:
  - "@rpetit3"
