#!/usr/bin/env python3
"""Propagate versions.yml into Bactopia's hand-maintained version-bearing files.

`versions.yml` at the repo root is the single, *manually edited* source of truth
for the pipeline version (`bactopia`) and the plugin pin (`nf-bactopia`). This
script only ever READS it, then copies those values into the files that carry a
literal version but are NOT regenerated by any other tool:

    conf/test_base.config   bactopia_version = '...'  and  id 'nf-bactopia@...'
    CITATION.cff            version: ...
    bin/bactopia            VERSION=...
    data/conda/meta.yaml    {% set version = '...' %}

Everything else that carries the version is a generated artifact and is left to
its regenerator: `nextflow.config` / workflow configs (bactopia-merge-schemas)
and `catalog.json` / `llms.txt` (bactopia-catalog). Those are a follow-up step,
not this script's job.

Only the exact version token inside each match is rewritten; surrounding text is
untouched. Runs are idempotent -- a file already at the target value is reported
as "current" and left byte-for-byte unchanged. This script NEVER writes
versions.yml.
"""

import argparse
import re
import sys
from pathlib import Path

DEFAULT_BP = "/home/rpetit3/repos/bactopia/bactopia"

# Each rule: (regex with three groups (prefix, version, suffix), versions.yml key,
# human label). The version token is group 2; prefix/suffix are preserved verbatim.
TARGETS: dict[str, list[tuple[str, str, str]]] = {
    "conf/test_base.config": [
        (r"(bactopia_version\s*=\s*')([^']+)(')", "bactopia", "bactopia_version"),
        (r"(id\s+'nf-bactopia@)([^']+)(')", "nf-bactopia", "nf-bactopia pin"),
    ],
    "CITATION.cff": [
        (r"(?m)(^version:[ \t]*)(\S+)()", "bactopia", "version"),
    ],
    "bin/bactopia": [
        (r"(?m)(^VERSION=)(\S+)()", "bactopia", "VERSION"),
    ],
    "data/conda/meta.yaml": [
        (r"(\{%\s*set version\s*=\s*')([^']+)(')", "bactopia", "set version"),
    ],
}


def read_versions(bp: Path) -> dict[str, str]:
    """Parse versions.yml (simple `key: value`; stdlib only). Never modified."""
    path = bp / "versions.yml"
    text = path.read_text()
    out: dict[str, str] = {}
    for line in text.splitlines():
        m = re.match(r"([\w-]+):\s*(\S+)", line)
        if m:
            out[m.group(1)] = m.group(2)
    for key in ("bactopia", "nf-bactopia"):
        if key not in out:
            raise KeyError(f"versions.yml missing required key '{key}'")
    return out


def apply_file(
    bp: Path, rel: str, rules: list[tuple[str, str, str]], versions: dict, check: bool
) -> list[dict]:
    """Return a list of change records for one file; write in place unless check."""
    path = bp / rel
    changes: list[dict] = []
    if not path.exists():
        return [{"file": rel, "label": "-", "status": "missing"}]
    text = path.read_text()
    new_text = text
    for pattern, key, label in rules:
        want = versions[key]
        rec = {"file": rel, "label": label, "want": want}
        m = re.search(pattern, new_text)
        if not m:
            rec["status"] = "pattern-not-found"
            changes.append(rec)
            continue
        old = m.group(2)
        rec["old"] = old
        if old == want:
            rec["status"] = "current"
        else:
            rec["status"] = "update"
            new_text = (
                new_text[: m.start(2)] + want + new_text[m.end(2) :]
            )
        changes.append(rec)
    if not check and new_text != text:
        path.write_text(new_text)
    return changes


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Propagate versions.yml into hand-maintained version files."
    )
    ap.add_argument("--bactopia-path", default=DEFAULT_BP)
    ap.add_argument(
        "--check",
        action="store_true",
        help="dry run: report what would change, write nothing",
    )
    args = ap.parse_args()
    bp = Path(args.bactopia_path)

    try:
        versions = read_versions(bp)
    except (FileNotFoundError, KeyError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    mode = "DRY RUN (no files written)" if args.check else "APPLY"
    print(f"[bump-versions] {mode}")
    print(
        f"  source versions.yml -> bactopia={versions['bactopia']}, "
        f"nf-bactopia={versions['nf-bactopia']}\n"
    )

    updated = missing = notfound = 0
    for rel, rules in TARGETS.items():
        for rec in apply_file(bp, rel, rules, versions, args.check):
            s = rec["status"]
            if s == "update":
                verb = "would update" if args.check else "updated"
                print(f"  [{verb}] {rel}: {rec['label']} {rec['old']} -> {rec['want']}")
                updated += 1
            elif s == "current":
                print(f"  [ok]  {rel}: {rec['label']} already {rec['want']}")
            elif s == "missing":
                print(f"  [WARN] {rel}: file not found")
                missing += 1
            elif s == "pattern-not-found":
                print(f"  [WARN] {rel}: could not locate {rec['label']} literal")
                notfound += 1

    print(
        f"\n[bump-versions] {'would update' if args.check else 'updated'} "
        f"{updated} value(s); warnings: {missing + notfound}"
    )
    if updated and not args.check:
        print(
            "\nNext steps (regenerated artifacts are NOT touched here):\n"
            "  1. /merge-schemas all   (nextflow.config + schemas from versions.yml)\n"
            "  2. /update-catalog      (catalog.json + llms.txt)\n"
            "  3. verify: bactopia-lint repo tier -> V001/V002/V003 should pass\n"
            "  4. smoke-test a module whose test container tag changed."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
