Bootstrap: docker
From: nfcore/base

%labels
    MAINTAINER Robert A. Petit III <robert.petit@emory.edu>
    DESCRIPTION Singularity image for Bactopia Tool fastani
    VERSION 1.5.x

%environment
    PATH=/opt/conda/envs/bactopia-fastani/bin:$PATH
    export PATH

%files
    tools/fastani/environment.yml /

%post
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin/conda clean -a
