name: tblastx
description: Search against translated nucleotide databases using a translated nucleotide query
icon: false
keywords:
  - fasta
  - blast
  - alignment
modules:
  - tblastx
input:
  - meta:
    type: map
    description: |
      Groovy Map containing sample information
      e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Input fasta file containing queries sequences
      pattern: "*.{fa,fasta}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: TBLASTX results in TSV format
      pattern: "*.tblastx.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of TBLASTX results for all samples
      pattern: "*.tsv"
docs:
  meta:
    title: tblastx
    description: >
      A Bactopia Tool which uses TBLASTX to query translated nucleotide sequences against translated nucleotide databases.
  introduction: |
      The `tblastx` module uses [TBLASTX](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=Blastdocs)
      to query translated nucleotide sequences against translated nucleotide databases for each sample.
  output:
    tree: |
      <BACTOPIA_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── tblastx
      │           ├── <SAMPLE_NAME>.tblastx.tsv
      │           └── logs
      │               ├── nf-tblastx.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── bactopia-runs
          └── tblastx-<TIMESTAMP>
              ├── merged-results
              │   ├── tblastx.tsv
              │   └── logs
              │       └── tblastx-concat
              │           ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │           └── versions.yml
              └── nf-reports
                  ├── tblastx-dag.dot
                  ├── tblastx-report.html
                  ├── tblastx-timeline.html
                  └── tblastx-trace.txt
    add_note: false
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: tblastx.tsv
            description: A merged TSV file with `tblastx` results from all samples
      - name: tblastx
        description: |
          Below is a description of the _per-sample_ results from [TBLASTX](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=Blastdocs).
        table:
          - id: <SAMPLE_NAME>.tblastx.tsv
            description: A TSV file with `tblastx` results for a single sample
  citations:
    - blast
    - csvtk
