name: emmtyper
description: EMM typing of Streptococcus pyogenes assemblies
keywords:
  - streptococcus
  - pyogenes
  - emm
  - typing
tools:
  - emmtyper:
      description: "emm typing tool for Streptococcus pyogenes assemblies"
      homepage: "https://github.com/MDU-PHL/emmtyper"
      documentation: "https://github.com/MDU-PHL/emmtyper"
      tool_dev_url: "https://github.com/MDU-PHL/emmtyper"
      doi: ""
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Assembly in FASTA format
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"
  - blastdb:
      type: file
      description: Optional custom BLAST database
      pattern: "*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: Tab-delimited emmtyper results
      pattern: "*.tsv"
  - logs:
      type: file
      description: Standard log files
      pattern: "*.{log,err}"
  - nf_logs:
      type: file
      description: Nextflow log files
      pattern: ".command.*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
