name: shigeifinder
description: Cluster informed identification of both Shigella and EIEC
keywords:
  - Shigella
  - EIEC
  - virulence
  - ipaH
  - cluster
tools:
  - shigeifinder:
      description: A tool for differentiation and characterization of Shigella/EIEC using cluster-specific genes
      homepage: https://github.com/LanLab/ShigEiFinder
      documentation: https://github.com/LanLab/ShigEiFinder
      tool_dev_url: https://github.com/LanLab/ShigEiFinder
      doi: "10.1099/mgen.0.000704"
      licence: ['GPL v3']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file containing the genome assembly
      pattern: "*.{fasta,fna,fa,fasta.gz,fna.gz,fa.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: ShigEiFinder results in TSV format
      pattern: "*.tsv"
authors:
  - "@rpetit3"
