name: checkm_lineagewf
description: CheckM provides a set of tools for assessing the quality of bacterial and archaeal genomes
keywords:
  - quality assessment
  - completeness
  - contamination
  - bacteria
  - archaea
tools:
  - checkm:
      description: |
        CheckM provides a set of tools for assessing the quality of genomes
        recovered from isolates, single cells, or metagenomes.
      homepage: https://github.com/Ecogenomics/CheckM
      documentation: https://github.com/Ecogenomics/CheckM/wiki
      tool_dev_url: https://github.com/Ecogenomics/CheckM
      doi: 10.1101/gr.186072.114
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Genome assembly in FASTA format
      pattern: "*.{fa,fna,fasta,fa.gz,fna.gz,fasta.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - results:
      type: file
      description: Directory containing all CheckM output files
      pattern: "results/*"
  - tsv:
      type: file
      description: CheckM results in tab-delimited format
      pattern: "*-results.txt"
  - logs:
      type: file
      description: Process logs
      pattern: "*.{log,err}"
  - nf_begin:
      type: file
      description: Nextflow begin file
      pattern: ".command.begin"
  - nf_err:
      type: file
      description: Nextflow error file
      pattern: ".command.err"
  - nf_log:
      type: file
      description: Nextflow log file
      pattern: ".command.log"
  - nf_out:
      type: file
      description: Nextflow output file
      pattern: ".command.out"
  - nf_run:
      type: file
      description: Nextflow run file
      pattern: ".command.run"
  - nf_sh:
      type: file
      description: Nextflow script file
      pattern: ".command.sh"
  - nf_trace:
      type: file
      description: Nextflow trace file
      pattern: ".command.trace"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@rpetit3"
