name: spatyper
description: Computational method for finding spa types in _Staphylococcus aureus_
icon: false
tags:
  - fasta
  - serotype
  - Staphylococcus aureus
modules:
  - spatyper
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"
  - repeats:
      type: file
      description: spa repeat sequences in FASTA format (Optional)
      pattern: "*.{fasta}"
  - repeat_order:
      type: file
      description: spa types and order of repeats (Optional)
      pattern: "*.{txt}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - tsv:
      type: file
      description: Per-sample summary of the spaTyper assessement
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged summary of the spaTyper assessement
      pattern: "spatyper.tsv"
docs:
  meta:
    title: spatyper
    description: >-
      A Bactopia Tool which uses spaTyper to assign _spa_ types to
      _Staphylococcus aureus_ assemblies.
  introduction:
    The `spatyper` module uses [spaTyper](https://github.com/HCGB-IGTP/spaTyper) to assign
    _spa_ types to _Staphylococcus aureus_ assemblies.
  output:
    tree: |
      <BACTOPIA_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── spatyper
      │           ├── <SAMPLE_NAME>.tsv
      │           └── logs
      │               ├── nf-spatyper.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── bactopia-runs
          └── spatyper-<TIMESTAMP>
              ├── merged-results
              │   ├── logs
              │   │   └── spatyper-concat
              │   │       ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │   │       └── versions.yml
              │   └── spatyper.tsv
              └── nf-reports
                  ├── spatyper-dag.dot
                  ├── spatyper-report.html
                  ├── spatyper-timeline.html
                  └── spatyper-trace.txt
    add_note: true
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: spatyper.tsv
            description: A merged TSV file with `spaTyper` results from all samples
      - name: spaTyper
        description: |
          Below is a description of the _per-sample_ results from [spaTyper](https://github.com/HCGB-IGTP/spaTyper).
        table:
          - id: <SAMPLE_NAME>.tsv
            description: A tab-delimited file with `spaTyper` result
  citations:
    - csvtk
    - spatyper
    - spatyper_db
