name: abricate
description: Mass screening of contigs for antimicrobial and virulence genes
keywords:
  - bacteria
  - fasta
  - antimicrobial resistance
modules:
  - abricate
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - assembly:
      type: file
      description: The final assembly in FASTA format
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: Tab-delimited report of results for a single sample
      pattern: "*.{txt}"
  - merged_tsv:
      type: file
      description: Tab-delimited report of results from all samples
      pattern: "*.{txt}"
docs:
  meta:
    title: abricate
    description: >-
      A Bactopia Tool which uses Abricate to screen assemblies for antimicrobial 
      resistance and virulence genes
  introduction: |
    The `abricate` module uses [Abricate](https://github.com/tseemann/abricate) to screen assemblies
    for antimicrobial resistance and virulence genes.
  output:
    tree: |
      <BACTOPIA_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── abricate
      │           ├── <SAMPLE_NAME>.txt
      │           └── logs
      │               ├── nf-abricate.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── bactopia-runs
          └── abricate-<TIMESTAMP>
              ├── merged-results
              │   ├── abricate.tsv
              │   └── logs
              │       └── abricate-concat
              │           ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │           └── versions.yml
              └── nf-reports
                  ├── abricate-dag.dot
                  ├── abricate-report.html
                  ├── abricate-timeline.html
                  └── abricate-trace.txt
    add_note: false
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: abricate.tsv
            description: A merged TSV file with `Abricate` results from all samples
      - name: Abricate
        description: |
          Below is a description of the _per-sample_ results from [Abricate](https://github.com/tseemann/abricate).
        table:
          - id: <SAMPLE_NAME>.txt
            description: A tab-delimited report of hits, for full details please see [Abricate - Output](https://github.com/tseemann/abricate#output)
  citations:
    - abricate
    - arg_annot
    - card
    - csvtk
    - ecoh
    - megares2
    - ncbi_reference_gene_catolog
    - plasmidfinder
    - resfinder
    - vfdb
